/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as MinersRouteImport } from './routes/miners'
import { Route as MaintainersRouteImport } from './routes/maintainers'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AppRouteImport } from './routes/app'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ApiIndexRouteImport } from './routes/api.index'
import { Route as DocsUpstreamDriftRouteImport } from './routes/docs.upstream-drift'
import { Route as DocsTroubleshootingRouteImport } from './routes/docs.troubleshooting'
import { Route as DocsScoreabilityRouteImport } from './routes/docs.scoreability'
import { Route as DocsQuickstartRouteImport } from './routes/docs.quickstart'
import { Route as DocsPrivacySecurityRouteImport } from './routes/docs.privacy-security'
import { Route as DocsMinerWorkflowRouteImport } from './routes/docs.miner-workflow'
import { Route as DocsMcpClientsRouteImport } from './routes/docs.mcp-clients'
import { Route as DocsMaintainerWorkflowRouteImport } from './routes/docs.maintainer-workflow'
import { Route as DocsMaintainerInstallTrustRouteImport } from './routes/docs.maintainer-install-trust'
import { Route as DocsGithubAppRouteImport } from './routes/docs.github-app'
import { Route as DocsBranchAnalysisRouteImport } from './routes/docs.branch-analysis'
import { Route as DocsBetaOnboardingRouteImport } from './routes/docs.beta-onboarding'
import { Route as DocsAiSummariesRouteImport } from './routes/docs.ai-summaries'
import { Route as AppWorkbenchRouteImport } from './routes/app.workbench'
import { Route as AppRunsRouteImport } from './routes/app.runs'
import { Route as AppReposRouteImport } from './routes/app.repos'
import { Route as AppPlaygroundRouteImport } from './routes/app.playground'
import { Route as AppOwnerRouteImport } from './routes/app.owner'
import { Route as AppOperatorRouteImport } from './routes/app.operator'
import { Route as AppMinerRouteImport } from './routes/app.miner'
import { Route as AppMaintainerRouteImport } from './routes/app.maintainer'
import { Route as AppDigestRouteImport } from './routes/app.digest'
import { Route as AppCommandsRouteImport } from './routes/app.commands'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as ApiOpRouteImport } from './routes/api.$op'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const MinersRoute = MinersRouteImport.update({
  id: '/miners',
  path: '/miners',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintainersRoute = MaintainersRouteImport.update({
  id: '/maintainers',
  path: '/maintainers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiRoute,
} as any)
const DocsUpstreamDriftRoute = DocsUpstreamDriftRouteImport.update({
  id: '/upstream-drift',
  path: '/upstream-drift',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTroubleshootingRoute = DocsTroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => DocsRoute,
} as any)
const DocsScoreabilityRoute = DocsScoreabilityRouteImport.update({
  id: '/scoreability',
  path: '/scoreability',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQuickstartRoute = DocsQuickstartRouteImport.update({
  id: '/quickstart',
  path: '/quickstart',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPrivacySecurityRoute = DocsPrivacySecurityRouteImport.update({
  id: '/privacy-security',
  path: '/privacy-security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMinerWorkflowRoute = DocsMinerWorkflowRouteImport.update({
  id: '/miner-workflow',
  path: '/miner-workflow',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMcpClientsRoute = DocsMcpClientsRouteImport.update({
  id: '/mcp-clients',
  path: '/mcp-clients',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMaintainerWorkflowRoute = DocsMaintainerWorkflowRouteImport.update({
  id: '/maintainer-workflow',
  path: '/maintainer-workflow',
  getParentRoute: () => DocsRoute,
} as any)
const DocsMaintainerInstallTrustRoute =
  DocsMaintainerInstallTrustRouteImport.update({
    id: '/maintainer-install-trust',
    path: '/maintainer-install-trust',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsGithubAppRoute = DocsGithubAppRouteImport.update({
  id: '/github-app',
  path: '/github-app',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBranchAnalysisRoute = DocsBranchAnalysisRouteImport.update({
  id: '/branch-analysis',
  path: '/branch-analysis',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBetaOnboardingRoute = DocsBetaOnboardingRouteImport.update({
  id: '/beta-onboarding',
  path: '/beta-onboarding',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAiSummariesRoute = DocsAiSummariesRouteImport.update({
  id: '/ai-summaries',
  path: '/ai-summaries',
  getParentRoute: () => DocsRoute,
} as any)
const AppWorkbenchRoute = AppWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppOperatorRoute = AppOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AppRoute,
} as any)
const AppMinerRoute = AppMinerRouteImport.update({
  id: '/miner',
  path: '/miner',
  getParentRoute: () => AppRoute,
} as any)
const AppMaintainerRoute = AppMaintainerRouteImport.update({
  id: '/maintainer',
  path: '/maintainer',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestRoute = AppDigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandsRoute = AppCommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const ApiOpRoute = ApiOpRouteImport.update({
  id: '/$op',
  path: '/$op',
  getParentRoute: () => ApiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/ai-summaries': typeof DocsAiSummariesRoute
  '/docs/beta-onboarding': typeof DocsBetaOnboardingRoute
  '/docs/branch-analysis': typeof DocsBranchAnalysisRoute
  '/docs/github-app': typeof DocsGithubAppRoute
  '/docs/maintainer-install-trust': typeof DocsMaintainerInstallTrustRoute
  '/docs/maintainer-workflow': typeof DocsMaintainerWorkflowRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/miner-workflow': typeof DocsMinerWorkflowRoute
  '/docs/privacy-security': typeof DocsPrivacySecurityRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/scoreability': typeof DocsScoreabilityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/upstream-drift': typeof DocsUpstreamDriftRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/changelog': typeof ChangelogRoute
  '/extension': typeof ExtensionRoute
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/ai-summaries': typeof DocsAiSummariesRoute
  '/docs/beta-onboarding': typeof DocsBetaOnboardingRoute
  '/docs/branch-analysis': typeof DocsBranchAnalysisRoute
  '/docs/github-app': typeof DocsGithubAppRoute
  '/docs/maintainer-install-trust': typeof DocsMaintainerInstallTrustRoute
  '/docs/maintainer-workflow': typeof DocsMaintainerWorkflowRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/miner-workflow': typeof DocsMinerWorkflowRoute
  '/docs/privacy-security': typeof DocsPrivacySecurityRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/scoreability': typeof DocsScoreabilityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/upstream-drift': typeof DocsUpstreamDriftRoute
  '/api': typeof ApiIndexRoute
  '/app': typeof AppIndexRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/api': typeof ApiRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/extension': typeof ExtensionRoute
  '/maintainers': typeof MaintainersRoute
  '/miners': typeof MinersRoute
  '/roadmap': typeof RoadmapRoute
  '/api/$op': typeof ApiOpRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/commands': typeof AppCommandsRoute
  '/app/digest': typeof AppDigestRoute
  '/app/maintainer': typeof AppMaintainerRoute
  '/app/miner': typeof AppMinerRoute
  '/app/operator': typeof AppOperatorRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/playground': typeof AppPlaygroundRoute
  '/app/repos': typeof AppReposRoute
  '/app/runs': typeof AppRunsRoute
  '/app/workbench': typeof AppWorkbenchRoute
  '/docs/ai-summaries': typeof DocsAiSummariesRoute
  '/docs/beta-onboarding': typeof DocsBetaOnboardingRoute
  '/docs/branch-analysis': typeof DocsBranchAnalysisRoute
  '/docs/github-app': typeof DocsGithubAppRoute
  '/docs/maintainer-install-trust': typeof DocsMaintainerInstallTrustRoute
  '/docs/maintainer-workflow': typeof DocsMaintainerWorkflowRoute
  '/docs/mcp-clients': typeof DocsMcpClientsRoute
  '/docs/miner-workflow': typeof DocsMinerWorkflowRoute
  '/docs/privacy-security': typeof DocsPrivacySecurityRoute
  '/docs/quickstart': typeof DocsQuickstartRoute
  '/docs/scoreability': typeof DocsScoreabilityRoute
  '/docs/troubleshooting': typeof DocsTroubleshootingRoute
  '/docs/upstream-drift': typeof DocsUpstreamDriftRoute
  '/api/': typeof ApiIndexRoute
  '/app/': typeof AppIndexRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/api'
    | '/app'
    | '/changelog'
    | '/docs'
    | '/extension'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/commands'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/ai-summaries'
    | '/docs/beta-onboarding'
    | '/docs/branch-analysis'
    | '/docs/github-app'
    | '/docs/maintainer-install-trust'
    | '/docs/maintainer-workflow'
    | '/docs/mcp-clients'
    | '/docs/miner-workflow'
    | '/docs/privacy-security'
    | '/docs/quickstart'
    | '/docs/scoreability'
    | '/docs/troubleshooting'
    | '/docs/upstream-drift'
    | '/api/'
    | '/app/'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/changelog'
    | '/extension'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/commands'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/ai-summaries'
    | '/docs/beta-onboarding'
    | '/docs/branch-analysis'
    | '/docs/github-app'
    | '/docs/maintainer-install-trust'
    | '/docs/maintainer-workflow'
    | '/docs/mcp-clients'
    | '/docs/miner-workflow'
    | '/docs/privacy-security'
    | '/docs/quickstart'
    | '/docs/scoreability'
    | '/docs/troubleshooting'
    | '/docs/upstream-drift'
    | '/api'
    | '/app'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/api'
    | '/app'
    | '/changelog'
    | '/docs'
    | '/extension'
    | '/maintainers'
    | '/miners'
    | '/roadmap'
    | '/api/$op'
    | '/app/analytics'
    | '/app/commands'
    | '/app/digest'
    | '/app/maintainer'
    | '/app/miner'
    | '/app/operator'
    | '/app/owner'
    | '/app/playground'
    | '/app/repos'
    | '/app/runs'
    | '/app/workbench'
    | '/docs/ai-summaries'
    | '/docs/beta-onboarding'
    | '/docs/branch-analysis'
    | '/docs/github-app'
    | '/docs/maintainer-install-trust'
    | '/docs/maintainer-workflow'
    | '/docs/mcp-clients'
    | '/docs/miner-workflow'
    | '/docs/privacy-security'
    | '/docs/quickstart'
    | '/docs/scoreability'
    | '/docs/troubleshooting'
    | '/docs/upstream-drift'
    | '/api/'
    | '/app/'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ApiRoute: typeof ApiRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  ExtensionRoute: typeof ExtensionRoute
  MaintainersRoute: typeof MaintainersRoute
  MinersRoute: typeof MinersRoute
  RoadmapRoute: typeof RoadmapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miners': {
      id: '/miners'
      path: '/miners'
      fullPath: '/miners'
      preLoaderRoute: typeof MinersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintainers': {
      id: '/maintainers'
      path: '/maintainers'
      fullPath: '/maintainers'
      preLoaderRoute: typeof MaintainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/': {
      id: '/api/'
      path: '/'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof ApiRoute
    }
    '/docs/upstream-drift': {
      id: '/docs/upstream-drift'
      path: '/upstream-drift'
      fullPath: '/docs/upstream-drift'
      preLoaderRoute: typeof DocsUpstreamDriftRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/troubleshooting': {
      id: '/docs/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/docs/troubleshooting'
      preLoaderRoute: typeof DocsTroubleshootingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/scoreability': {
      id: '/docs/scoreability'
      path: '/scoreability'
      fullPath: '/docs/scoreability'
      preLoaderRoute: typeof DocsScoreabilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/quickstart': {
      id: '/docs/quickstart'
      path: '/quickstart'
      fullPath: '/docs/quickstart'
      preLoaderRoute: typeof DocsQuickstartRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/privacy-security': {
      id: '/docs/privacy-security'
      path: '/privacy-security'
      fullPath: '/docs/privacy-security'
      preLoaderRoute: typeof DocsPrivacySecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/miner-workflow': {
      id: '/docs/miner-workflow'
      path: '/miner-workflow'
      fullPath: '/docs/miner-workflow'
      preLoaderRoute: typeof DocsMinerWorkflowRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/mcp-clients': {
      id: '/docs/mcp-clients'
      path: '/mcp-clients'
      fullPath: '/docs/mcp-clients'
      preLoaderRoute: typeof DocsMcpClientsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/maintainer-workflow': {
      id: '/docs/maintainer-workflow'
      path: '/maintainer-workflow'
      fullPath: '/docs/maintainer-workflow'
      preLoaderRoute: typeof DocsMaintainerWorkflowRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/maintainer-install-trust': {
      id: '/docs/maintainer-install-trust'
      path: '/maintainer-install-trust'
      fullPath: '/docs/maintainer-install-trust'
      preLoaderRoute: typeof DocsMaintainerInstallTrustRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/github-app': {
      id: '/docs/github-app'
      path: '/github-app'
      fullPath: '/docs/github-app'
      preLoaderRoute: typeof DocsGithubAppRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/branch-analysis': {
      id: '/docs/branch-analysis'
      path: '/branch-analysis'
      fullPath: '/docs/branch-analysis'
      preLoaderRoute: typeof DocsBranchAnalysisRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/beta-onboarding': {
      id: '/docs/beta-onboarding'
      path: '/beta-onboarding'
      fullPath: '/docs/beta-onboarding'
      preLoaderRoute: typeof DocsBetaOnboardingRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai-summaries': {
      id: '/docs/ai-summaries'
      path: '/ai-summaries'
      fullPath: '/docs/ai-summaries'
      preLoaderRoute: typeof DocsAiSummariesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/app/workbench': {
      id: '/app/workbench'
      path: '/workbench'
      fullPath: '/app/workbench'
      preLoaderRoute: typeof AppWorkbenchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/runs': {
      id: '/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/repos': {
      id: '/app/repos'
      path: '/repos'
      fullPath: '/app/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/playground': {
      id: '/app/playground'
      path: '/playground'
      fullPath: '/app/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operator': {
      id: '/app/operator'
      path: '/operator'
      fullPath: '/app/operator'
      preLoaderRoute: typeof AppOperatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/miner': {
      id: '/app/miner'
      path: '/miner'
      fullPath: '/app/miner'
      preLoaderRoute: typeof AppMinerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/maintainer': {
      id: '/app/maintainer'
      path: '/maintainer'
      fullPath: '/app/maintainer'
      preLoaderRoute: typeof AppMaintainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/digest': {
      id: '/app/digest'
      path: '/digest'
      fullPath: '/app/digest'
      preLoaderRoute: typeof AppDigestRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commands': {
      id: '/app/commands'
      path: '/commands'
      fullPath: '/app/commands'
      preLoaderRoute: typeof AppCommandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/$op': {
      id: '/api/$op'
      path: '/$op'
      fullPath: '/api/$op'
      preLoaderRoute: typeof ApiOpRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface ApiRouteChildren {
  ApiOpRoute: typeof ApiOpRoute
  ApiIndexRoute: typeof ApiIndexRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiOpRoute: ApiOpRoute,
  ApiIndexRoute: ApiIndexRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommandsRoute: typeof AppCommandsRoute
  AppDigestRoute: typeof AppDigestRoute
  AppMaintainerRoute: typeof AppMaintainerRoute
  AppMinerRoute: typeof AppMinerRoute
  AppOperatorRoute: typeof AppOperatorRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppReposRoute: typeof AppReposRoute
  AppRunsRoute: typeof AppRunsRoute
  AppWorkbenchRoute: typeof AppWorkbenchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommandsRoute: AppCommandsRoute,
  AppDigestRoute: AppDigestRoute,
  AppMaintainerRoute: AppMaintainerRoute,
  AppMinerRoute: AppMinerRoute,
  AppOperatorRoute: AppOperatorRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppReposRoute: AppReposRoute,
  AppRunsRoute: AppRunsRoute,
  AppWorkbenchRoute: AppWorkbenchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DocsRouteChildren {
  DocsAiSummariesRoute: typeof DocsAiSummariesRoute
  DocsBetaOnboardingRoute: typeof DocsBetaOnboardingRoute
  DocsBranchAnalysisRoute: typeof DocsBranchAnalysisRoute
  DocsGithubAppRoute: typeof DocsGithubAppRoute
  DocsMaintainerInstallTrustRoute: typeof DocsMaintainerInstallTrustRoute
  DocsMaintainerWorkflowRoute: typeof DocsMaintainerWorkflowRoute
  DocsMcpClientsRoute: typeof DocsMcpClientsRoute
  DocsMinerWorkflowRoute: typeof DocsMinerWorkflowRoute
  DocsPrivacySecurityRoute: typeof DocsPrivacySecurityRoute
  DocsQuickstartRoute: typeof DocsQuickstartRoute
  DocsScoreabilityRoute: typeof DocsScoreabilityRoute
  DocsTroubleshootingRoute: typeof DocsTroubleshootingRoute
  DocsUpstreamDriftRoute: typeof DocsUpstreamDriftRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAiSummariesRoute: DocsAiSummariesRoute,
  DocsBetaOnboardingRoute: DocsBetaOnboardingRoute,
  DocsBranchAnalysisRoute: DocsBranchAnalysisRoute,
  DocsGithubAppRoute: DocsGithubAppRoute,
  DocsMaintainerInstallTrustRoute: DocsMaintainerInstallTrustRoute,
  DocsMaintainerWorkflowRoute: DocsMaintainerWorkflowRoute,
  DocsMcpClientsRoute: DocsMcpClientsRoute,
  DocsMinerWorkflowRoute: DocsMinerWorkflowRoute,
  DocsPrivacySecurityRoute: DocsPrivacySecurityRoute,
  DocsQuickstartRoute: DocsQuickstartRoute,
  DocsScoreabilityRoute: DocsScoreabilityRoute,
  DocsTroubleshootingRoute: DocsTroubleshootingRoute,
  DocsUpstreamDriftRoute: DocsUpstreamDriftRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ApiRoute: ApiRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  ExtensionRoute: ExtensionRoute,
  MaintainersRoute: MaintainersRoute,
  MinersRoute: MinersRoute,
  RoadmapRoute: RoadmapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
